In [3]:
import numpy as np


In [4]:
# Create a NumPy array with values from 10 to 50, stepping by 5
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
# Turn the array above into a 5×10 matrix
np.arange(10,50).reshape(4,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [6]:
# Given an array arr = np.array([1, 2, 3, 4, 5]), write code to square each element without using a loop.
arr = np.array([1, 2, 3, 4, 5])
print(np.array([1, 2, 3, 4, 5])*np.array([1, 2, 3, 4, 5]))

[ 1  4  9 16 25]


In [12]:
# Given an array arr = np.array([1, 2, 3, 4, 5]), write code to square each element without using a loop.
arr = np.array([1, 2, 3, 4, 5])
number = arr ** 2
print(number)

[ 1  4  9 16 25]


In [7]:
#If you have an array a = np.array([[1, 2], [3, 4], [5, 6]]), how do you extract [3, 5]?
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(a[1:3, :1])

[[3]
 [5]]


In [13]:
import pandas as pd

In [14]:
# Create a DataFrame with two columns: Name and Age, with 3 rows of sample data

info = {
    "Name": ["Esther","Favour","Joy"],
    "Age": [12,7,3]
    }

pd.DataFrame(info)

Name  Age
0  Esther   12
1  Favour    7
2     Joy    3

In [57]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [24, 28, 35, 22]
}
df = pd.DataFrame(data)
df

Name  Age
0   John   24
1   Anna   28
2  Peter   35
3  Linda   22

In [58]:
# Given the following data

import pandas as pd
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [24, 28, 35, 22]
}
df = pd.DataFrame(data)
# What is the total age of all the students?
df["Age"]
print(sum(df["Age"]))

109


In [70]:
# How would you extract the records of Peter and Linda from the code above

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [24, 28, 35, 22]
}


print(df[2:])

    Name  Age
2  Peter   35
3  Linda   22


In [71]:
filtered_df = df[df['Name'].isin(['Peter', 'Linda'])]

print(filtered_df)


    Name  Age
2  Peter   35
3  Linda   22


In [27]:
import pandas as pd

In [30]:
# Import this data using pandas
# https://raw.githubusercontent.com/waleolajumoke/data/refs/heads/main/Student.csv

# importing data

df=pd.read_csv("https://raw.githubusercontent.com/waleolajumoke/data/refs/heads/main/Student.csv")
df


gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [33]:
# Find out the statistical summary of the data
df.describe()

math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [35]:
# Check out missing values in the data
df.isnull()

gender  race/ethnicity  parental level of education  lunch  \
0     False           False                        False  False   
1     False           False                        False  False   
2     False           False                        False  False   
3     False           False                        False  False   
4     False           False                        False  False   
..      ...             ...                          ...    ...   
995   False           False                        False  False   
996   False           False                        False  False   
997   False           False                        False  False   
998   False           False                        False  False   
999   False           False                        False  False   

     test preparation course  math score  reading score  writing score  
0                      False       False          False          False  
1                      False       False          False          False  
2                      False       False          False          False  
3                      False       False          False          False  
4                      False       False          False          False  
..                       ...         ...            ...            ...  
995                    False       False          False          False  
996                    False       False          False          False  
997                    False       False          False          False  
998                    False       False          False          False  
999                    False       False          False          False  

[1000 rows x 8 columns]

In [36]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64